//export const CHECK_LOGIN_DATA="CHECK_LOGIN_DATA";
export const ADD_NEW_USER="ADD_NEW_USER";
export const ADD_NEW_BLOG="ADD_NEW_BLOG";
export const GET_NEW_BLOG="GET_NEW_BLOG";
export const IS_LOGGED_IN="IS_LOGGED_IN";
export const IS_GET_PERMISSION="IS_GET_PERMISSION"
