export const ADD_NEW_USER="ADD_NEW_USER";
export const ADD_NEW_ASSIGNMENT="ADD_NEW_ASSIGNMENT";
export const GET_ASSIGNMENTS="GET_ASSIGNMENTS";
export const IS_LOGGED_IN="IS_LOGGED_IN";
export const GET_PERMISSIONS="GET_PERMISSIONS"
